

function VisionPage() {
    return (
        <main className="container mx-auto flex min-h-screen flex-col items-center space-y-10 mt-10 p-4">
            <h1 className="text-4xl font-bold">Our Vision</h1>
            <p className="text-white text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum diam urna, molestie congue lacus quis, ullamcorper hendrerit magna. Duis a feugiat sapien, a iaculis metus. Fusce tempus rutrum justo, ac rutrum velit sollicitudin nec. Nulla eu nulla eros. Proin pellentesque purus ac tristique bibendum. Morbi augue dolor, mattis eget odio et, feugiat dapibus justo. In sed justo molestie, vehicula sapien eget, finibus nunc. Phasellus erat purus, pulvinar at tellus lobortis, cursus ornare risus. Duis vel sodales arcu. Integer consectetur viverra mi, quis dapibus turpis elementum vitae. Donec eget dignissim nisi. Duis mauris odio, accumsan vitae urna tempor, pharetra aliquam erat. Vestibulum mattis vestibulum massa, in commodo metus vulputate et. Donec in risus convallis, posuere ante sed, lacinia libero. Proin ut varius massa, eu dapibus ex.
                Cras quis gravida libero, nec semper odio. Maecenas sodales augue dolor, quis ullamcorper libero tempus nec. Phasellus tincidunt vulputate risus vel condimentum. Vivamus euismod id magna et consequat. Nunc lorem tellus, euismod lobortis diam ac, interdum gravida ligula. Donec mattis sodales mi eget vestibulum. Duis rutrum auctor tellus, sed lacinia nunc hendrerit in. Duis id commodo nulla. Mauris pulvinar blandit purus nec dapibus. Sed sed dui est. Pellentesque id justo viverra, pharetra leo eget, molestie leo. Ut faucibus metus cursus, dapibus orci eu, ullamcorper diam. Curabitur in egestas ligula. Suspendisse nibh erat, molestie sit amet erat vel, sodales placerat quam. Sed ac eros euismod, accumsan felis vitae, iaculis ante.
                Aliquam erat volutpat. Curabitur sollicitudin diam libero, in ullamcorper dui pretium id. Donec scelerisque laoreet dui eget tincidunt. Suspendisse non velit risus. Curabitur at rhoncus nunc. Nulla facilisi. Sed vitae turpis eu enim pulvinar sodales non rhoncus tellus. Nulla vestibulum ante velit, ut varius lorem vestibulum at. Ut ultrices libero sed nulla placerat, vitae aliquam magna faucibus. Integer ultrices mi ut elit dictum iaculis ut nec massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris sed dolor eget diam suscipit feugiat ut a ipsum. Vestibulum porttitor, lectus ac bibendum gravida, nisi nisl commodo lectus, sed iaculis enim lacus malesuada sapien. Morbi non odio in sem varius feugiat eu sit amet odio. In placerat fermentum dui eu semper. Suspendisse potenti.
                Ut pulvinar enim nunc, at auctor augue ultrices id. Sed pulvinar non nunc id fringilla. Maecenas quis felis vitae lectus aliquet pretium. Etiam id enim vitae justo porta tempus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus ac tortor sed odio placerat sollicitudin quis eget metus. Donec vestibulum arcu id ornare molestie. Curabitur sit amet massa in risus dapibus ultrices. Vestibulum nisi nisi, commodo a odio id, consequat facilisis elit.
                Cras at fringilla eros, ut mollis lacus. Nulla neque elit, sollicitudin quis vehicula in, suscipit eget metus. Sed sollicitudin, metus a iaculis ullamcorper, augue leo vehicula purus, tristique ullamcorper risus urna et eros. Fusce non erat eu nunc fringilla tristique non eget lorem. Fusce ultrices venenatis felis sit amet molestie. Suspendisse semper, sem ac ullamcorper lobortis, est odio imperdiet turpis, vitae accumsan ipsum velit egestas dolor. Mauris quis interdum metus. Aliquam malesuada finibus enim vitae rhoncus.
            </p>
        </main>
    )
}

export default VisionPage